# Fancying-up the prompt
export TERM="xterm-256color"
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)

# sudo apt install zsh-theme-powerlevel9k
source  /usr/share/powerlevel9k/powerlevel9k.zsh-theme

# Enable syntax highlighting and autosuggestions
# sudo apt install zsh-syntax-highlighting
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Fuzzy finder
export FZF_DEFAULT_OPTS='--height 20% --reverse --border'
# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# ~/.fzf/install
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# Enable completions
autoload -Uz compinit
compinit

# Persistent history
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=10000              #Number of history entries to save to disk
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# Aliases
# cargo install exa
alias ls=exa
# sudo apt install neovim
alias vim=nvim
alias build="cargo fmt && cargo build && cargo clippy"

export EDITOR=nvim
export VISUAL=nvim

# Rust specific config
export LD_LIBRARY_PATH=/usr/local/lib
export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH

