export TERM="xterm-256color"

bindkey -e
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line
bindkey "[b" backward-word
bindkey "[f" forward-word

# git clone https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k
source ~/.powerlevel10k/powerlevel10k.zsh-theme

# Enable syntax highlighting and autosuggestions
# brew install zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# brew install zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Fuzzy finder
export FZF_DEFAULT_OPTS='--height 20% --reverse --border'
# brew install fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Enable completions
autoload -Uz compinit
compinit

# Persistent history
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=10000              #Number of history entries to save to disk
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# Aliases
# cargo install exa
alias ls=exa
# brew install neovim
alias vim=nvim

export EDITOR=nvim
export VISUAL=nvim

# Rust specific config
export PATH=$PATH:$HOME/.cargo/bin:$HOME/.local/bin:/usr/local/bin

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
